name: Activation team PR checklist
on:
  pull_request:
    types: [opened, labeled]

jobs:
  comment:
    if: github.event.label.name == 'activation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const msg = `Did you make changes to the subscription pages?
            Please verify that everything still works by going through the
            (Subscription checklist)[https://epidemicsound.atlassian.net/wiki/spaces/TECH/pages/2566750376/Subscription+checklist]`

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
